const { test, expect } = require("@playwright/test");
test("signup → add task → toggle → delete", async ({ page }) => {
    await page.goto("/");
    const email = `u${Date.now()}@example.com`;
    await page.getByPlaceholder("email").fill(email);
    await page.getByPlaceholder("password").fill("secret123");
    await page.getByRole("button", { name: "Sign up" }).click();
    await expect(page.getByRole("heading", { name: "Tasks" })).toBeVisible();
    await page.getByPlaceholder("New task").fill("Interview prep");
    await page.getByRole("button", { name: "Add" }).click();
    const item = page.locator("li", { hasText: "Interview prep" });
    await expect(item).toBeVisible();
    const checkbox = item.locator('input[type="checkbox"]');
    await expect(checkbox).not.toBeChecked();
    const patchOk = page.waitForResponse((res) => res.request().method() === "PATCH" && /\/api\/tasks\/\d+$/.test(res.url()) && res.status() === 200);
    await checkbox.click();
    await patchOk;
    await expect(checkbox).toBeChecked();
    await expect(item.locator("span")).toHaveCSS("text-decoration-line", "line-through");
    await item.getByRole("button", { name: "Delete" }).click();
    await expect(item).toHaveCount(0);
});